sex-list: ["fuck", "gay片", "g点", "h动画", "h动漫"]
advertisement-list: ["兼职", "招聘", "网络", "QQ", "招聘", "有意者", "到货", "本店", "代购", "扣扣"]
politics-list: ["习近平", "平近习", "xjp", "习太子"]
violence-list: ["出售雷管", "炸药", "炸药", "出售炸药", "出售美军现役军刀"]
default-list: ["英语的网红App", "招～小～説～ 打～芓~员", "@诚，邀@咑，牸，人，员", "xck855"]